# matrix generator
DIMENSION_X = 10
DIMENSION_Y = 25

BLOCK_SIZE = 32
SCREEN_WIDTH = DIMENSION_Y * BLOCK_SIZE
SCREEN_HEIGHT = DIMENSION_X * BLOCK_SIZE
HALF_BLOCK_SIZE = BLOCK_SIZE / 2
QUARTER_BLOCK_SIZE = BLOCK_SIZE / 4

# colors
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
BLUE = (0, 0, 255)
GREEN = (0, 255, 0)
RED = (255, 0, 0)

MAX_LEVEL = 1
MAX_LIFE_LEVEL = 1

RECORDS_PATH = 'records.csv'
GRID_FILE = './src/grid.txt'

ENEMIES_HEURISTIC_CONSTANT = 20
MAX_ALFA_BETTA_RECURSION = 18
